theme: jekyll-theme-minimal
title: Lorenzo Crippa
logo: https://lh3.googleusercontent.com/9VHvTXpQ6mHZP1I89yvFJlq4qMlolGj7M7fKiV_ofDlEWy7G0WJ4DA3E2ANPAMxhiIkEauxOqViQ2Zn1S2F0SBqnPNxa-ZjJ6fcUeW1C_-yRh-baZg=w1280

description: University of Essex, Department of Government
