# Site settings
title: Lorenzo Crippa
email: l.crippa@essex.ac.uk
logo: /assets/LorenzoCrippa.jpg
description: > # this means to ignore newlines until "baseurl:"
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://lorenzo-crippa.github.io" # the base hostname & protocol for your site
twitter_username: CrippaLorenzo
github_username:  lorenzo-crippa
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
