theme: jekyll-theme-minimal
title: Lorenzo Crippa

# User settings
#username: lorem ipsum
#user_title: Lorem Ipsum - FrontEnd
email: l.crippa@essex.ac.uk
twitter_username: CrippaLorenzo
#github_username:  loremipsum
#gplus_username:  loremipsum
#linkedin_public_url: loremipsum # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
#disqus_username: loremipsum
profile_picture: https://lh6.googleusercontent.com/NONclYPuAjBz-kqvL5D_Cf67YPBkNf0100PWtWGx3VUtKyx4g_riCSNh7kA1NaMHRJCBqBkQ9JPWUKRfiAPCuaequ-DI4oQWFIHTQIKIE9iDXBwJAQ=w1280
